iad_training:
    resource: "@iadTrainingBundle/Resources/config/routing.yml"
    prefix:   /

iad_training_default:
    resource: "@iadTrainingBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
